language: go

go:
  - 1.12.4

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

install:
  - go get -v resenje.org/web/...

before_script:
  - go vet -v resenje.org/web/...

script:
  - go test -v resenje.org/web/...
